# Generated by Django 5.1.1 on 2024-09-10 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='assinatura_digital',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='receita',
            name='assinatura_digital',
            field=models.FileField(blank=True, null=True, upload_to='assinaturas_receitas/'),
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='assinaturas/')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='clinica.prontuario')),
            ],
        ),
    ]
