# Generated by Django 5.1.1 on 2024-09-11 00:44

import clinica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_prontuario_assinatura_digital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='arquivo',
            field=models.FileField(upload_to='assinaturas/', validators=[clinica.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=20, unique=True, validators=[clinica.models.validate_crm]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(validators=[clinica.models.validate_data_nascimento]),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='assinatura_digital',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='assinatura_digital',
            field=models.TextField(blank=True, null=True),
        ),
    ]
