# Generated by Django 5.1.1 on 2024-09-11 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_alter_assinatura_arquivo_alter_medico_crm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=255)),
                ('dosagem', models.CharField(max_length=50)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='clinica.receita')),
            ],
        ),
    ]
