# Generated by Django 5.1.1 on 2024-09-11 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0007_prontuario_medico_alter_medico_crm_alter_medico_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.medico'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.medico'),
        ),
    ]
