# Generated by Django 5.1.1 on 2024-09-11 02:15

import clinica.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_alter_prontuario_medico_alter_receita_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dosagem', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=20, unique=True, validators=[clinica.models.validate_crm]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(validators=[clinica.models.validate_data_nascimento]),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='assinatura_digital',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/', validators=[clinica.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='receita',
            name='assinatura_digital',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/', validators=[clinica.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='receita',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medicamento'),
        ),
    ]
