# Generated by Django 5.1.1 on 2024-09-11 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_medicamento_alter_medico_crm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='dosagem',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='medicamento',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='medicamento',
            field=models.CharField(default='Sem Medicamento', max_length=255),
        ),
        migrations.AlterField(
            model_name='itemreceita',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medicamento'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='dosagem',
            field=models.CharField(max_length=255),
        ),
    ]
