# Generated by Django 5.1.1 on 2024-09-11 04:16

import clinica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0010_remove_medicamento_descricao_remove_medicamento_nome_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='receita',
            options={'ordering': ['-data'], 'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
        migrations.AlterField(
            model_name='itemreceita',
            name='dosagem',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='dosagem',
            field=models.CharField(default='Sem dosagem', max_length=255),
        ),
        migrations.AlterField(
            model_name='receita',
            name='assinatura_digital',
            field=models.ImageField(blank=True, null=True, upload_to='receitas/', validators=[clinica.models.validate_file_extension]),
        ),
    ]
